# Run build, unit tests. Then publish to 'tools' folder and commit back to repository
# It will run on every push or PR if any file in 'source' folder is changed
name: Build and test on push or pull request

on:
  push:
    branches: [ "main" ]
    paths:
      - 'source/**' 
      - '.github/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'source/**'
      - '.github/**' 

jobs:
  build:

    #runs-on: windows-latest
    runs-on: ubuntu-latest
    
    env:
      SolutionPath: source/IndexBuild/IndexBuild.sln
      ProjectPath: source/IndexBuild/IndexBuilder/IndexBuilder.csproj
      _Configuration: Release
      _Platform: linux-x64
      #_Platform: win-x64
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
       
    - name: Restore dependencies
      run: dotnet restore $SolutionPath
            
    - name: Build
      run: dotnet build --configuration Release --no-restore $SolutionPath
      #run: dotnet build --configuration Release source/IndexBuild/IndexBuild.sln
      #if: ${{true}}
            
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal $SolutionPath
      #if: ${{false}}
 
    - name: Publish
      #run: dotnet publish -c $_Configuration -r $_Platform --no-restore -p:PublishSingleFile=true --self-contained $ProjectPath
      run: dotnet publish -c $_Configuration -r $_Platform -p:PublishSingleFile=true --self-contained $ProjectPath

    - name: List
      run: ls source/IndexBuild/IndexBuilder/bin/Release/net7.0/linux-x64/publish

    - name: Copy into tools folder
      run: |
        mkdir -p tools
        cp source/IndexBuild/IndexBuilder/bin/Release/net7.0/linux-x64/publish/IndexBuilder /tools/IndexBuilder
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}